### ISSUE TITLE
"attribute x.exampleSetFlag is unexpected" errors during OpenAPI generation

### ISSUE THREAD

**Issue by Spiess** [vitrivr/CineastUnityInterface#1]
Attempting to generate the Cineast OpenAPI bindings causes errors during spec validation.

The errors are all in the form of "attribute <qualified name>.exampleSetFlag is unexpected".
Some examples:
```
Errors: 
	-attribute components.schemas.QueryConfig.exampleSetFlag is unexpected
	-attribute components.schemas.Tag.exampleSetFlag is unexpected
	-attribute components.schemas.Credentials.exampleSetFlag is unexpected
```

A temporary workaround has already been implemented in the form of the skipValidateSpec flag in build.gradle.

This issue has been reproduced using both the gradle OpenAPI generator and the CLI OpenAPI generator through docker.
The issue may lie with the generation of the OpenAPI spec within Cineast.

**Comment by lucaro** [comment]
Iirc, this was a known-issue with a previous version of the openapi generator. Updating the javalin dependency to the latest version should fix this.

**Comment by Spiess** [comment]
With the current version of the Cineast OpenAPI specs this is no longer an issue and validation works as expected.
